/*
 * #%L
 * wcm.io
 * %%
 * Copyright (C) 2015 wcm.io
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package io.wcm.caravan.hal.docs.impl.augmenter;

import org.apache.commons.lang3.StringUtils;

import io.wcm.caravan.commons.stream.Streams;
import io.wcm.caravan.hal.resource.HalResource;
import io.wcm.caravan.hal.resource.Link;

/**
 * Checks if the HAL resource contains link relations without title.
 * Adds titles from the HAL documentation generated by this bundle.
 */
class LinkRelationTitleAugmenter {

  private final DocsMetadata metadata;

  LinkRelationTitleAugmenter(DocsMetadata metadata) {
    this.metadata = metadata;
  }

  public void augment(HalResource resource) {
    Streams.of(resource.getLinks().entries())
    .forEach(entry -> augmentLink(entry.getKey(), entry.getValue()));
  }

  public void augmentLink(String rel, Link link) {
    if (StringUtils.isBlank(link.getTitle())) {
      link.setTitle(metadata.getLinkRelationTitle(rel));
    }
  }

}
